from a1d05eba1.content_variations import build_content


KOBOXLSFORM_EXAMPLE_1 = {'choices': [{'$autovalue': 'dogs',
              '$kuid': 'EX_KUID_1',
              'label': ['Dogs'],
              'list_name': 'animals',
              'name': 'dogs'},
             {'$autovalue': 'cats',
              '$kuid': 'RMN0tkXAI',
              'label': ['Cats'],
              'list_name': 'animals',
              'name': 'cats'},
             {'$autovalue': 'reptiles',
              '$kuid': 'Z4o5n9rLI',
              'label': ['Reptiles'],
              'list_name': 'animals',
              'name': 'reptiles'},
             {'$autovalue': 'birds',
              '$kuid': '2RGWh9WnO',
              'label': ['Birds'],
              'list_name': 'animals',
              'name': 'birds'}],
 'schema': '1',
 'settings': {},
 'survey': [{'$autoname': 'start',
             '$kuid': '7lYlsW2DX',
             'name': 'start',
             'type': 'start'},
            {'$autoname': 'end',
             '$kuid': 'sn0UGzUES',
             'name': 'end',
             'type': 'end'},
            {'$autoname': 'Hello',
             '$kuid': 'hi5qs55',
             'label': ['Hello'],
             'required': False,
             'type': 'note'},
            {'$autoname': 'What_is_your_name',
             '$kuid': 'nz7fm41',
             'label': ['What is your name?'],
             'required': False,
             'type': 'text'},
            {'$autoname': 'What_animals_do_you_like',
             '$kuid': 'rk3nr85',
             'label': ['What animals do you like?'],
             'required': False,
             'select_from_list_name': 'animals',
             'type': 'select_multiple'}],
 'translated': ['label'],
 'translations': [None]}

KOBOXLSFORM_EXAMPLE_2 = {'choices': [{'label': ['Dogs'],
              'list_name': 'animals',
              'name': 'dogs'},
             {'label': ['Cats'],
              'list_name': 'animals',
              'name': 'cats'},
             {'label': ['Reptiles'],
              'list_name': 'animals',
              'name': 'reptiles'},
             {'label': ['Birds'],
              'list_name': 'animals',
              'name': 'birds'}],
 'schema': '1',
 'settings': {},
 'survey': [{'$autoname': 'start',
             '$kuid': '7lYlsW2DX',
             'name': 'start',
             'type': 'start'},
            {'$autoname': 'end',
             '$kuid': 'sn0UGzUES',
             'name': 'end',
             'type': 'end'},
            {'$autoname': 'Hello',
             '$kuid': 'hi5qs55',
             'label': ['Hello'],
             'required': False,
             'type': 'note'},
            {'$autoname': 'What_is_your_name',
             '$kuid': 'nz7fm41',
             'label': ['What is your name?'],
             'required': False,
             'type': 'text'},
            {'$autoname': 'What_animals_do_you_like',
             '$kuid': 'rk3nr85',
             'label': ['What animals do you like?'],
             'required': False,
             'select_from_list_name': 'animals',
             'type': 'select_multiple'}],
 'translated': ['label'],
 'translations': [None]}

def test_anchors():
    kuid01 = 'EX_KUID_1'
    content = KOBOXLSFORM_EXAMPLE_1
    assert content['choices'][0]['$kuid'] == kuid01
    kk = build_content(content)
    assert kk.choices._insides.uf['animals'][0]._anchor == kuid01
    exp = kk.export_to('2')
    assert exp['choices']['animals'][0]['$anchor'] == 'EX_KUID_1'
